# Generated by Django 2.2.1 on 2019-05-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('list',)},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['-sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='list',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
