# Generated by Django 2.2.1 on 2019-05-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190519_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('list', '-sort_order')},
        ),
        migrations.AddField(
            model_name='card',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
