# Generated by Django 2.2.1 on 2019-05-05 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190504_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Task'),
        ),
        migrations.AlterField(
            model_name='user',
            name='boards',
            field=models.ManyToManyField(null=True, to='todo.Board'),
        ),
    ]
