# Generated by Django 2.2.1 on 2019-05-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190519_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('list', 'sort_order')},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['sort_order', 'id']},
        ),
    ]
