# Generated by Django 2.2.1 on 2019-05-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_board_list_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lists',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.List'),
        ),
    ]
