# Generated by Django 2.2.1 on 2019-05-22 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190519_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('sort_order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('sort_order', 'id')},
        ),
    ]
