# Generated by Django 2.2.1 on 2019-05-05 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190505_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='boards',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Board'),
        ),
    ]
