# Generated by Django 2.2.1 on 2019-05-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20190505_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
        migrations.AlterField(
            model_name='user',
            name='boards',
            field=models.ManyToManyField(to='todo.Board'),
        ),
    ]
