# Generated by Django 2.2.1 on 2019-05-05 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20190505_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='boards',
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
