# Generated by Django 2.2.1 on 2019-05-06 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20190505_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='boards',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='descriptions',
            new_name='description',
        ),
    ]
