# Generated by Django 2.2.1 on 2019-05-12 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_auto_20190512_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='board',
        ),
        migrations.RemoveField(
            model_name='task',
            name='list',
        ),
        migrations.AddField(
            model_name='board',
            name='lists',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.List'),
        ),
        migrations.AddField(
            model_name='list',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Task'),
        ),
    ]
