# Generated by Django 2.2.1 on 2019-05-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_auto_20190512_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='lists',
        ),
        migrations.AddField(
            model_name='board',
            name='lists',
            field=models.ManyToManyField(to='todo.List'),
        ),
    ]
